@startuml
'--- Class Diagram: Robot states

class Robot

interface RobotState { +tick(ctx: Robot) }
class OffState implements RobotState
class IdleState implements RobotState
class NavigatingState implements RobotState
class ChargingState implements RobotState
class ManipulatingState implements RobotState

class Robot {
  - state: RobotState
  + set_state(s: RobotState)
  + tick()
}

Robot --> RobotState : delegates
RobotState <|.. OffState
RobotState <|.. IdleState
RobotState <|.. NavigatingState
RobotState <|.. ChargingState
RobotState <|.. ManipulatingState
@enduml
