name: ci
on: [push, pull_request]
jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - run: python -m pip install -U pip pylint radon
      - run: python -m unittest discover -s robot/tests -p "test_*.py" -v
      - run: pylint robot --score y
      - run: radon cc -s -a robot
      - run: radon mi -s robot
